---
apiVersion: v2
appVersion: 4.2.3
description: Free and easy binary newsreader
name: sabnzbd
version: 10.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - sabnzbd
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
sources:
  - https://sabnzbd.org/
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://netanel-m.github.io/library-charts
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
