---
apiVersion: v2
appVersion: 2.3
description: Looks and smells like Sonarr but made for music
name: lidarr
version: 15.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - lidarr
  - torrent
  - usenet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/lidarr
icon: https://github.com/lidarr/Lidarr/blob/develop/Logo/512.png?raw=true
sources:
  - https://github.com/Lidarr/Lidarr
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: https://netanel-m.github.io/library-charts
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
