---
apiVersion: v2
appVersion: 7.2.3
description: NZBHydra2
name: nzbhydra
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - nzb
  - usernet
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/calibre-web
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/calibre-web-icon.png
sources:
  - https://hub.docker.com/r/linuxserver/calibre-web/
  - https://github.com/janeczku/calibre-web
maintainers:
  - name: wojoinc
    email: wojoinc@pm.me
dependencies:
  - name: common
    repository: https://netanel-m.github.io/library-charts
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
